[package]
name = "columnar"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
description = "Conversion from arrays of complex structs to simple structs of arrays"
edition = "2021"

# These URLs point to more information about the repository
documentation = "http://github.com/frankmcsherry/columnar"
homepage = "http://github.com/frankmcsherry/columnar"
repository = "https://github.com/frankmcsherry/columnar.git"
license = "MIT"
